<?php

namespace App\Http\Controllers;

use App\Models\Wallet;
use App\Models\CreditTransaction;
use App\Models\RedemptionCode;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Exception;

class WalletController extends Controller
{
    /**
     * Helper to process expired codes JIT (Just-In-Time) for a user.
     */
    private function processExpiredCodesForUser($userId)
    {
        $now = Carbon::now();
        
        $expiredCodes = RedemptionCode::where('status', 'active')
            ->where('expires_at', '<', $now)
            ->whereHas('transaction', function ($q) use ($userId) {
                $q->where('wallet_id', $userId);
            })
            ->with('transaction')
            ->get();

        foreach ($expiredCodes as $code) {
            DB::transaction(function () use ($code, $userId) {
                // Update code status
                $code->status = 'expired';
                $code->save();

                // Refund the amount (amount in initial txn is negative, so we do abs)
                CreditTransaction::create([
                    'id' => Str::uuid()->toString(),
                    'wallet_id' => $userId,
                    'amount' => abs($code->transaction->amount),
                    'type' => 'refund',
                    'description' => 'Reembolso automático por expiración de código de canje ' . $code->code,
                    'reference_id' => $code->id,
                    'created_at' => Carbon::now()
                ]);
            });
        }
    }

    /**
     * GET /api/wallet/balance
     * Returns the wallet balance and recent transaction history, processing expired codes first.
     */
    public function getBalance(Request $request)
    {
        $authUser = $request->input('auth_user');

        if (!$authUser || !isset($authUser['id'])) {
            return response()->json(['error' => 'No autorizado.'], 401);
        }

        $userId = $authUser['id'];

        try {
            // Process any expired code before reading balance
            $this->processExpiredCodesForUser($userId);

            // Fetch Wallet
            $wallet = Wallet::where('user_id', $userId)->first();
            if (!$wallet) {
                // Fallback creation if trigger failed
                $wallet = Wallet::create(['user_id' => $userId, 'balance' => 0.00]);
            }

            // Fetch Transactions
            $transactions = CreditTransaction::where('wallet_id', $userId)
                ->orderBy('created_at', 'desc')
                ->get();

            // Fetch Active Redemption Codes generated by user
            $activeCodes = RedemptionCode::where('status', 'active')
                ->whereHas('transaction', function ($q) use ($userId) {
                    $q->where('wallet_id', $userId);
                })
                ->with('partner:id,full_name')
                ->get();

            return response()->json([
                'balance' => (float) $wallet->balance,
                'transactions' => $transactions,
                'active_codes' => $activeCodes
            ]);

        } catch (Exception $e) {
            return response()->json([
                'error' => 'Error al obtener la información de la billetera.',
                'message' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * GET /api/partners
     * List all shop partners (comercios aliados) for the student selection.
     */
    public function getPartners()
    {
        try {
            $partners = User::where('role', 'partner')
                ->select('id', 'full_name', 'email', 'avatar_url')
                ->orderBy('full_name', 'asc')
                ->get();

            return response()->json($partners);
        } catch (Exception $e) {
            return response()->json([
                'error' => 'Error al obtener comercios aliados.',
                'message' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * POST /api/wallet/redeem/code
     * Generates a temporary 8-digit redemption code, reserving the amount in user's ledger.
     */
    public function generateRedemptionCode(Request $request)
    {
        $authUser = $request->input('auth_user');

        if (!$authUser || !isset($authUser['id'])) {
            return response()->json(['error' => 'No autorizado.'], 401);
        }

        $userId = $authUser['id'];

        $validated = $request->validate([
            'amount' => 'required|numeric|min:0.5',
            'partner_shop_id' => 'required|uuid|exists:users,id'
        ]);

        $amount = $validated['amount'];
        $partnerId = $validated['partner_shop_id'];

        // Verify partner role
        $partner = User::where('id', $partnerId)->where('role', 'partner')->first();
        if (!$partner) {
            return response()->json(['error' => 'El comercio seleccionado no es un socio comercial aliado válido.'], 400);
        }

        try {
            // Process any expired codes to guarantee accurate balance representation
            $this->processExpiredCodesForUser($userId);

            $wallet = Wallet::where('user_id', $userId)->first();
            if (!$wallet || $wallet->balance < $amount) {
                return response()->json(['error' => 'Saldo insuficiente para realizar el canje.'], 400);
            }

            $codeText = 'UNACH-' . strtoupper(Str::random(6));

            DB::beginTransaction();

            // 1. Create debit transaction
            $transaction = CreditTransaction::create([
                'id' => Str::uuid()->toString(),
                'wallet_id' => $userId,
                'amount' => -$amount, // Negative for debit
                'type' => 'shop_redemption',
                'description' => 'Reserva de créditos para canje en ' . $partner->full_name,
                'created_at' => Carbon::now()
            ]);

            // 2. Create Redemption Code
            $redemption = RedemptionCode::create([
                'id' => Str::uuid()->toString(),
                'transaction_id' => $transaction->id,
                'code' => $codeText,
                'status' => 'active',
                'partner_shop_id' => $partnerId,
                'expires_at' => Carbon::now()->addMinutes(10), // Expires in 10 minutes
            ]);

            DB::commit();

            return response()->json([
                'message' => 'Código de canje generado con éxito.',
                'code' => $redemption->code,
                'expires_at' => $redemption->expires_at,
                'amount' => $amount
            ], 201);

        } catch (Exception $e) {
            DB::rollBack();
            return response()->json([
                'error' => 'Error al generar el código de canje.',
                'message' => $e->getMessage()
            ], 500);
        }
    }

    /**
     * POST /api/partner/redeem/claim
     * Shop partner claims a redemption code scan/input.
     */
    public function claimRedemptionCode(Request $request)
    {
        $authUser = $request->input('auth_user');

        if (!$authUser || $authUser['role'] !== 'partner') {
            return response()->json(['error' => 'No autorizado. Se requiere rol de Comercio Aliado.'], 403);
        }

        $partnerId = $authUser['id'];

        $validated = $request->validate([
            'code' => 'required|string|max:12'
        ]);

        $codeText = strtoupper($validated['code']);

        try {
            $redemption = RedemptionCode::where('code', $codeText)->with('transaction')->first();

            if (!$redemption) {
                return response()->json(['error' => 'El código de canje proporcionado no existe.'], 404);
            }

            if ($redemption->status === 'claimed') {
                return response()->json(['error' => 'Este código ya ha sido reclamado previamente.'], 400);
            }

            if ($redemption->status === 'expired') {
                return response()->json(['error' => 'Este código ya ha expirado.'], 400);
            }

            if ($redemption->partner_shop_id !== $partnerId) {
                return response()->json(['error' => 'Este código fue reservado para otro comercio y no puede ser reclamado por ti.'], 400);
            }

            // Check expiration
            $now = Carbon::now();
            if (Carbon::parse($redemption->expires_at)->isBefore($now)) {
                // Process expiration JIT
                DB::transaction(function () use ($redemption) {
                    $redemption->status = 'expired';
                    $redemption->save();

                    CreditTransaction::create([
                        'id' => Str::uuid()->toString(),
                        'wallet_id' => $redemption->transaction->wallet_id,
                        'amount' => abs($redemption->transaction->amount),
                        'type' => 'refund',
                        'description' => 'Reembolso por expiración de código de canje detectado al reclamar ' . $redemption->code,
                        'reference_id' => $redemption->id,
                        'created_at' => Carbon::now()
                    ]);
                });

                return response()->json(['error' => 'Este código de canje ha expirado y los créditos fueron devueltos al estudiante.'], 400);
            }

            // Process Claim
            DB::beginTransaction();

            // 1. Mark as claimed
            $redemption->status = 'claimed';
            $redemption->claimed_at = Carbon::now();
            $redemption->save();

            // 2. Fetch original debit transaction details
            $debitTx = $redemption->transaction;
            $studentId = $debitTx->wallet_id;
            $amount = abs($debitTx->amount);

            // Fetch student name for description
            $student = User::find($studentId);
            $studentName = $student ? $student->full_name : 'Estudiante';

            // 3. Create credit transaction for shop partner
            CreditTransaction::create([
                'id' => Str::uuid()->toString(),
                'wallet_id' => $partnerId,
                'amount' => $amount, // Positive credit
                'type' => 'shop_redemption',
                'description' => 'Canje de créditos reclamado por servicios prestados a ' . $studentName . ' (Código: ' . $codeText . ')',
                'reference_id' => $redemption->id,
                'created_at' => Carbon::now()
            ]);

            DB::commit();

            return response()->json([
                'message' => 'Canje procesado con éxito. Se han acreditado ' . number_format($amount, 2) . ' UNACH-Credits a tu cuenta.',
                'amount' => $amount,
                'student_name' => $studentName
            ]);

        } catch (Exception $e) {
            DB::rollBack();
            return response()->json([
                'error' => 'Error al reclamar el código de canje.',
                'message' => $e->getMessage()
            ], 500);
        }
    }
}
